---

- name: Install debian https transport
  apt:
    name: apt-transport-https
    state: present

- name: Install signing key
  apt_key:
    url: https://www.cherokeesofidaho.org/public/stretch/GPG_KEY
    state: present

- name: Install debian {{ debian_version }} repo tychosoft
  apt_repository:
    repo: deb https://www.cherokeesofidaho.org/public/{{ debian_version}}/ ./
    state: present
    filename: tychosoft-public

