---

- name: Install debian https transport
  apt:
    name: apt-transport-https
    state: present

- name: Install signing key
  apt_key:
    url: "{{ debian_repo }}/GPG_KEY"
    state: present

- name: Install debian {{ debian_version }} repo tychosoft
  apt_repository:
    repo: deb {{ debian_repo }}/ {{ debian_path }}
    state: present
    filename: tychosoft-public

- name: Update tychosoft repo
  command: apt-get update -o Dir::Etc::sourcelist="sources.list.d/tychosoft-public.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  args:
    warn: false
  changed_when: 0
