---

- name: Install debian https transport
  apt:
    name: apt-transport-https
    state: present

- name: Install signing key
  apt_key:
    url: "{{ debian_repo }}/GPG_KEY"
    state: present

- name: Install debian {{ debian_version }} repo tychosoft
  apt_repository:
    repo: deb {{ debian_repo }}/ {{ debian_path }}
    state: present
    filename: tychosoft-public

