---

- include: debian-setup.yml
  when: ansible_distribution == "Debian"

- include: ubuntu-setup.yml
  when: ansible_distribution == "Ubuntu"

- name: Install server packages
  apt:
    name: "{{ server_packages }}"
    state: present

# definately want services stopped/inactive before any updates processed

- name: Config sipwitchqt server
  template:
    src: templates/sipwitchqt.conf.j2
    dest: /etc/sipwitchqt.conf
    mode: 0640
    owner: "{{ sip_server_identity }}"
    group: "{{ sip_server_identity }}"

- name: Config mariadb server
  template:
    src: templates/90-raspberrypi.cnf.j2
    dest: /etc/mysql/mariadb.conf.d
    mode: 0644

- name: Define piwitch systemd service
  template:
    src: templates/piwitch.service.j2
    dest: /lib/systemd/system/piwitch.service
    mode: 0644

- name: Stop services
  systemd: name="{{item}}" state=stopped daemon_reload=true
  with_items:
    - "{{system_services}}"

