---

- include: debian-setup.yml
  when: ansible_distribution == "Debian"

- include: ubuntu-setup.yml
  when: ansible_distribution == "Ubuntu"

- name: Install server packages
  apt:
    name: "{{ server_packages }}"
    state: present

# definately want services stopped/inactive before any updates processed

- name: Config sipwitchqt server
  template:
    src: templates/sipwitchqt.conf.j2
    dest: /etc/sipwitchqt.conf
    mode: 0640
    owner: "{{ sip_server_identity }}"
    group: "{{ sip_server_identity }}"

- name: Config mariadb server
  template:
    src: templates/90-raspberrypi.cnf.j2
    dest: /etc/mysql/mariadb.conf.d
    mode: 0644

- name: Define piwitch system service
  template:
    src: templates/piwitch.init.j2
    dest: /etc/init.d/piwitch.init
    mode: 0755

- name: Enable piwitch system service
  service: name=piwitch enabled=true

- name: Stop services
  service: name="{{ item }}" state=stopped
  with_items:
    - "{{ system_services }}"

