---

- include: debian-setup.yml
  when: ansible_distribution == "Debian"

- include: ubuntu-setup.yml
  when: ansible_distribution == "Ubuntu"

- name: Update repo cache
  apt:
    update_cache: yes

- name: Install server packages
  apt:
    name: "{{ server_packages }}"
    state: latest

# definately want services stopped/inactive before any updates processed

- name: Stop services
  systemd: name="{{item}}" state=stopped 
  with_items:
    - "{{system_services}}"

- name: Config sipwitchqt server
  template:
    src: sipwitchqt.conf.j2
    dest: /etc/sipwitchqt.conf
    mode: 0640
    owner: "{{ sip_server_identity }}"
    group: "{{ sip_server_identity }}"

