---
# require class variable, singleton with global access methods
Style/ClassVars:
    Exclude:
        - webkit/webkit.rb

# prefer longer lines
Metrics/LineLength:
    Max: 240

# prefer deeper nesting
Metrics/BlockNesting:
    Max: 5

# prefer word lists direct
Style/WordArray:
    Enabled: false

# not documenting classes for now
Style/Documentation:
    Enabled: false

# false triggers for things that are not lambda members
Style/SymbolProc:
    Enabled: false

# makes it easy to add to lists
Style/TrailingCommaInArrayLiteral:
    Enabled: false

# prefer compact spacing
Layout/SpaceInsideHashLiteralBraces:
    Enabled: false

# prefer compact spacing
Layout/SpaceInsideBlockBraces:
    Enabled: false
