#!/usr/bin/env ansible-playbook
---

# This is used to create a new install or update an existing one
# Runs ansible-playbook -i inventory/hosts.ini install.yml

- hosts: server
  become: yes
  vars:
    debian_version: stretch
    update_packages:
    - sipwitchqt-server
    - sipwitchqt-utils
    server_packages:
    - mariadb-server
    - mariadb-client
    - ruby-posix-mq
    - ruby-mysql2
    - ruby-rack
    - ruby-sinatra
    - ruby-sinatra-contrib
    - ruby-json
    - python-mysqldb    # required for ansible mysql support
    - sipwitchqt-server
    - sipwitchqt-utils
    system_services:
    - sipwitchd
  pre_tasks:
    - name: Test if debian system
      command: test -f /etc/debian_version
  post_tasks:
    - name: Update server packages
      apt:
        name: "{{ update_packages }}"
        state: latest
    - name: Restart services
      systemd: name="{{item}}" state=restarted 
      with_items:
      - "{{system_services}}"
  roles:
    - server-setup
    - setup-utils       # needed for piwitch-bootstrap...
    - setup-webkit      # web support
    - install-db        # create db users, load from our schema
