#!/usr/bin/env ansible-playbook
---

# This is used to remove and cleanup most of piwitch.
# Runs ansible_playbook -i inventory/hosts.ini remove.yml

- hosts: server
  become: yes
  vars:
    remove_packages:
      - sipwitchqt-server
      - sipwitchqt-utils
  pre_tasks:
    - name: Test if debian system
      command: test -f /etc/debian_version
  roles:
    - remove-db
    - server-cleanup
    

