#!/usr/bin/env ansible-playbook
---

# This is used to remove and cleanup most of piwitch.
# Runs ansible-playbook -i inventory/hosts.ini remove.yml

- hosts: server
  become: yes
  vars:
    remove_packages:
      - sipwitchqt-server
      - sipwitchqt-utils
    stopped_services:
      - "{{ web_server }}"
      - sipwitchd
    restart_services:
      - "{{ web_server }}"
  pre_tasks:
    - name: Test if piwitch installed
      command: test -f /usr/sbin/piwitch-series
    - name: Stop services
      systemd: name="{{item}}" state=stopped 
      with_items:
      - "{{stopped_services}}"
  roles:
    - remove-db
    - server-cleanup
    

