---
- name: Get remote db series number
  command: piwitch-series
  register: db_series

- set_fact:
    db_version: "{{ db_series.stdout }}"

- name: Update by series
  include: series.yml
  with_items:
    - 8
    - 9
    - 10
    - 11
  when: item|int > db_version|int

