---
- name: Create database piwitch
  mysql_db:
    name: piwitch
    state: present

- name: Copy database schemas
  copy:
    src: "{{ item }}"
    dest: "/usr/share/schemas/"
    owner: "root"
    mode: 0644
  with_fileglob:
    - schemas/piwitch-*.sql

- name: Install database schemas
  mysql_db:
    name: piwitch
    state: import
    target: "/usr/share/schemas/{{ item | basename }}"
  with_fileglob:
    - schemas/piwitch-*.sql

- name: Bootstrap initial database
  command: piwitch-bootstrap

# This is used to apply schema fragments to upgrade older databases

- name: Get remote db series number
  command: piwitch-series
  register: db_series

- set_fact:
    db_version: "{{ db_series.stdout }}"

- name: Update by series
  include: series.yml
  with_items:
    - 8
    - 9
    - 10
    - 11
  when: item|int > db_version|int

