---
- name: Remove server packages
  apt:
    name: "{{ remove_packages }}"
    state: absent
    autoremove: true

- name: Disable piwitch service
  service: name=piwitch enabled=false

- name: Remove config files and piwitch services
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/init.d/piwitch.init
    - /etc/sipwitchqt.conf
    - /var/lib/sipwitchqt
    - /srv/piwitch

- name: Remove server utils
  file:
    path: "/usr/sbin/{{ item | basename }}"
    state: absent
  with_fileglob:
    - utils/*
