---

- name: Remove server packages
  apt:
    name: "{{ remove_packages }}"
    state: absent
    autoremove: yes

- name: Remove server configs
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/sipwitchqt.conf
    - /var/lib/sipwitchqt

- name: Remove server utils
  file:
    path: "/usr/sbin/{{ item | basename }}"
    state: absent
  with_fileglob:
    - utils/*

